# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: echo 'Setting up guru shifu. This may take around 5 minutes...'
    init: print 'init script' # runs during prebuild
    command: print 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
